### ISSUE TITLE
channel 实例 错误

### ISSUE THREAD

**Issue by heqiang** [shgopher/GOFamily#21]
func A(timeout time.Duration)int{
    ch := make(chan int)
    go func(){
        // 模拟耗时处理
        time.Sleep(time.Second + timeout)
        ch <-1
        fmt.Println("test ")
    }()
    select {
        case v := <-ch :
            return v
        # 应该是<- time.After(timeout)才对吧
        case time.After(timeout):  

            return -1
    }
}

**Comment by shgopher** [comment]
是的，多谢

**Comment by shgopher** [comment]
close
