### ISSUE TITLE
开发课程推荐列表

### ISSUE THREAD

**Issue by shgopher** [shgopher/GOFamily#3]
# 算法设计思想基础

> 本课程是北京大学屈婉玲教授的课，强烈推荐

本课程讲述了计算机中最常见最重要的几大思想：

- 递归
- 分治
- 动态规划
- 贪心
- 回溯

课程URL：https://www.icourse163.org/learn/PKU-1002525003#/learn/content

**Comment by googege** [comment]
# 数据结构基础
> 本课程是北京大学的数据结构基础课，同时也是国家级精品课，偏向介绍各种数据结构，跟屈老师的算法课合在一起就完美了 --- 各种数据结构+ 计算机基础5大算法思想

主要内容包括：

- 树
- 队列
- 图
- 字符串
- ...

课程URL：https://www.icourse163.org/learn/PKU-1002534001#/learn/announce

**Comment by googege** [comment]
## 动态规划专题讲解

https://www.bilibili.com/video/av27893462
