### ISSUE TITLE
想请教一个关于内存对齐的问题

### ISSUE THREAD

**Issue by ZenKaiii** [shgopher/GOFamily#79]
想请教个问题，在go语言代码的性能优化章节中，提到了进行内存对齐，但据我查资料发现，Go 语言的编译器会自动处理结构体的内存对齐，那我们显示地控制结构体的内存对齐是否还会对go语言代码性能有所提升？

**Comment by shgopher** [comment]
一般不用，某些特殊场景可能需要。比如，跟c结合的时候，比如结构体频繁被使用的时候
